import { RoleEnum } from '../@core/shared/enum/role.enum';
import { MenuItem } from '../@core/shared/model/menu-item.model';

export const MENU_ITEMS: MenuItem[] = [
  {
    title: 'Dashboard',
    icon: 'briefcase-outline',
    link: '/pages/dashboard/view',
    home: true,
    key: 'dashboard',
    hidden: true,
    roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR],
  },
  {
    title: 'MÓDULOS',
    group: true,
    key: 'modules',
  },
  {
    title: 'Matriculación',
    icon: 'book-open-outline',
    link: '/pages/registration/view',
    home: true,
    key: 'registration',
    roles: [RoleEnum.ESTUDIANTE],
  },
  {
    title: 'Registration Course',
    icon: 'bookmark-outline',
    link: '/pages/registration/list',
    key: 'registration-course',
    hidden: true,
    roles: [RoleEnum.ESTUDIANTE],
  },
  // {
  //   title: 'Approval Payment',
  //   icon: 'file-text-outline',
  //   link: '/pages/approval-payment/list',
  //   key: 'approval-payment',
  //   hidden: true,
  //   roles: [RoleEnum.ADMINISTRADOR, RoleEnum.COLLECTION],
  // },
  // {
  //   title: 'Reject Payment',
  //   icon: 'swap-outline',
  //   link: '/pages/reject-payment/list',
  //   key: 'reject-payment',
  //   hidden: true,
  //   roles: [RoleEnum.ADMINISTRADOR, RoleEnum.COLLECTION],
  // },
  // {
  //   title: 'Statement Account',
  //   icon: 'people-outline',
  //   link: '/pages/statement-account/list',
  //   key: 'statement-account',
  //   hidden: true,
  //   roles: [RoleEnum.ADMINISTRADOR, RoleEnum.COLLECTION],
  // },
  // {
  //   title: 'Ventas',
  //   icon: 'swap-outline',
  //   link: '/pages/sale',
  //   key: 'sale',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Cuentas',
  //   icon: 'people-outline',
  //   link: '/pages/account',
  //   key: 'account',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Reservas',
  //   icon: 'book-outline',
  //   link: '/pages/booking',
  //   key: 'booking',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Ticket',
  //   icon: 'bookmark-outline',
  //   link: '/pages/ticket',
  //   key: 'ticket',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Movimientos',
  //   icon: 'list-outline',
  //   link: '/pages/movement',
  //   key: 'movement',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Tickets',
  //   icon: 'file-text-outline',
  //   link: '/pages/client/ticket',
  //   key: 'ticket',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Mayoristas',
  //   icon: 'briefcase-outline',
  //   link: '/pages/company',
  //   key: 'company',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  // },
  // {
  //   title: 'Plataformas',
  //   icon: 'film-outline',
  //   link: '/pages/platform',
  //   key: 'platform',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT],
  // },
  // {
  //   title: 'ADMINISTRACIÓN',
  //   group: true,
  //   key: 'administration',
  // },
  {
    title: 'Matriculación',
    icon: 'list-outline',
    link: '/pages/enrollments/list',
    key: 'enrollments',
    hidden: true,
    roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR],
  },
  {
    title: 'Cursos',
    icon: 'grid-outline',
    link: '/pages/courses/list',
    key: 'courses',
    hidden: true,
    roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR],
  },
  {
    title: 'User Detail',
    icon: 'lock-outline',
    link: '/pages/users/list',
    key: 'user-detail',
    hidden: true,
    roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR],
  },
  {
    title: 'Contract',
    icon: 'file-text-outline',
    link: '/pages/contracts/list',
    key: 'contract',
    hidden: true,
    roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR],
  },

  // {
  //   title: 'Client Detail',
  //   icon: 'person-outline',
  //   link: '/pages/clients/list',
  //   key: 'client-detail',
  //   hidden: true,
  //   roles: [RoleEnum.ADMINISTRADOR],
  // },
  // {
  //   title: 'Settings',
  //   icon: 'list-outline',
  //   link: '/pages/settings/list',
  //   key: 'settings',
  //   hidden: true,
  //   roles: [RoleEnum.ADMINISTRADOR],
  // },
  // {
  //   title: 'Tables & Data',
  //   icon: 'grid-outline',
  //   key: 'tables',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  //   children: [
  //     {
  //       title: 'Mayoristas',
  //       icon: 'arrow-ios-forward-outline',
  //       link: '/pages/company',
  //       key: 'company',
  //       hidden: true,
  //       roles: [RoleEnum.ROOT, RoleEnum.ADMINISTRADOR, RoleEnum.ESTUDIANTE],
  //     },
  //     {
  //       title: 'Plataformas',
  //       icon: 'arrow-ios-forward-outline',
  //       link: '/pages/platform',
  //       key: 'platform',
  //       hidden: true,
  //       roles: [RoleEnum.ROOT],
  //     },
  //     {
  //       title: 'Cuentas',
  //       icon: 'arrow-ios-forward-outline',
  //       link: '/pages/account',
  //       key: 'account',
  //       hidden: true,
  //       roles: [RoleEnum.ROOT],
  //     },
  //   ],
  // },
  // {
  //   title: 'Auth',
  //   icon: 'lock-outline',
  //   key: 'auth',
  //   hidden: true,
  //   roles: [RoleEnum.ROOT],
  //   children: [
  //     {
  //       title: 'User',
  //       icon: 'person-outline',
  //       link: '/pages/user',
  //       key: 'users',
  //       hidden: true,
  //       roles: [RoleEnum.ROOT],
  //     },
  //   ],
  // },
];
