export enum BpmStatusEnum {
  COMPLETED = 'COMPLETED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXTERNALLY_TERMINATED = 'EXTERNALLY_TERMINATED',
  INTERNALLY_TERMINATED = 'INTERNALLY_TERMINATED',
}
