export enum StatusAccountEnum {
  PENDING = 'PENDING',
  ONHOLD = 'ONHOLD',
  TODELIVER = 'TODELIVER',
  ASSIGNED = 'ASSIGNED',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
  REPLACEMENT = 'REPLACEMENT',
}
