export enum TrnStatusEnum {
  NEW = 'NEW',
  CREATED = 'CREATED',
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  RELEASED = 'RELEASED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}
